### ISSUE TITLE
Import statement is not recognised

### ISSUE THREAD

**Issue by turkunov** [osm1um/amino.ts#2]

**Comment by turkunov** [comment]
Hello! 
I'm writing a bot for my Amino. I've downloaded all dependencies that you have mentioned in the documentation. Unfortunately, when I reference index.ts file ```const Amino = require("./src/index.ts");``` I keep getting the error message as follows: 
``` 
import { request } from "./request"
^^^^^^

SyntaxError: Cannot use import statement outside a module

**Comment by beryll1um** [comment]
I like to tell everyone that it's all because you don't put the stars in
the repository 😂

I don't have enough information, but maybe you just misrepresented the
module in TS. Chances are you'll need to use "import" to use the module.
It's also possible that you've erred in "tsconfig.json".
