### ISSUE TITLE
UPD docs

### ISSUE THREAD

**Issue by ParadiseFallen** [osm1um/amino.ts#3]
How to get device_id

You need https://play.google.com/store/apps/details?id=com.guoshi.httpcanary&hl=ru | HttpCannary app
And root. Install app and certificates from app. Logout from account. Start watch trafic in app. Log in. Find packet to https://service.narvii.com/api/v1/g/s/device, Open Request tab and select Raw. There in JSON DeviceId

**Comment by beryll1um** [comment]
I'll add a point about this to the docs. But I'm not going to advertise third-party applications. lol
